apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    path: guestbook
    repoURL: https://github.com/SMACAcademy/argocd-example-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
